---
- ignore: {name: Avoid lambda}
- ignore: {name: Use const}

- fixity: infixr 8 `Cons`
- fixity: infixr 4 !>
- fixity: infixl 7 \-
- fixity: infixr 0 ~>
- fixity: infixl 4 $>
- fixity: infix 9 +=
- fixity: infix 9 :=
- fixity: infixr 6 <#>
- fixity: infixr 5 <?>
- fixity: infixl 5 .|.
- fixity: infixl 7 .&.
