cabal-version:      2.2
name:               apple
version:            0.3.0.0
license:            AGPL-3.0-only
license-file:       LICENSE
copyright:          Copyright: (c) 2022 Vanessa McHale
maintainer:         vamchale@gmail.com
author:             Vanessa McHale
synopsis:           Apple array language compiler
description:        Compiler for a typed, APL-inspired array language.
category:           Language, Array
build-type:         Simple
data-files:         ./include/apple_abi.h
extra-source-files:
    bench/apple/*.🍏
    c/ffi.c
    i/ex/*.🍎
    i/ex/*.🍏
    i/golden/*.out
    include/apple.h
    include/apple_p.h
    include/m.h
    Makefile
    math/*.🍎
    math/*.🍏
    math/numbertheory/*.🍎
    math/numbertheory/*.🍏
    math/stats/*.🍎
    math/stats/*.🍏
    mk/os.mk
    pyc/*.c
    pyc/Makefile
    R/apple.R
    Rc/*.c
    Rc/Makefile
    test/data/*.🍎
    test/data/*.🍏
    test/examples/*.🍎
    test/examples/*.🍏
    test/harness/*.c

extra-doc-files:
    CHANGELOG.md
    README.md

source-repository head
    type:     git
    location: https://github.com/vmchale/apple

common warn
    default-language:   Haskell2010
    default-extensions:
        LambdaCase
        OverloadedStrings
        TupleSections

    ghc-options:
        -Wall -fno-warn-missing-signatures -Wno-x-partial
        -Wincomplete-uni-patterns -Wincomplete-record-updates
        -Wredundant-constraints -Widentities -Wmissing-export-lists
        -Wcpp-undef -Wunused-packages -Wno-operator-whitespace-ext-conflict

library
    import:             warn
    exposed-modules:
        Dbg
        A
        Asm.Aarch64
        Asm.M
        Asm.X86
        B
        CGen
        Hs.A
        L
        Nm
        P
        Parser
        Asm.Pr
        Prettyprinter.Ext
        Sh
        Ty
        Ty.M
        U

    build-tool-depends:
        , alex:alex    >=3.5.0.0
        , happy:happy  >=2.1

    hs-source-dirs:     src
    other-modules:
        A.C
        A.Eta
        A.Opt
        A.S
        Asm.Aarch64.B
        Asm.Aarch64.CF
        Asm.Aarch64.Fr
        Asm.Aarch64.Guess
        Asm.Aarch64.Opt
        Asm.Aarch64.P
        Asm.Aarch64.Sp
        Asm.Aarch64.T
        Asm.Ar
        Asm.Ar.P
        Asm.BB
        Asm.CF
        Asm.G
        Asm.G.Set
        Asm.L
        Asm.LI
        Asm.X86.B
        Asm.X86.CF
        Asm.X86.Frame
        Asm.X86.Opt
        Asm.X86.P
        Asm.X86.Sp
        Asm.X86.SpX
        Asm.X86.Trans
        Bits
        C
        C.Alloc
        C.CF
        C.Trans
        CF
        CF.AL
        Class.E
        Data.Copointed
        E
        I
        IR
        IR.C
        IR.CF
        IR.Hoist
        IR.Opt
        LI
        LR
        Nm.IntMap
        Nm.IntSet
        Op
        Parser.Rw
        Q
        R
        R.R
        Ty.Clone

    default-extensions:
        DeriveFoldable
        DeriveFunctor

    other-extensions:
        BinaryLiterals
        DeriveAnyClass
        DeriveGeneric
        FlexibleContexts
        GeneralizedNewtypeDeriving
        MagicHash
        MultiParamTypeClasses
        RankNTypes
        ScopedTypeVariables
        StandaloneDeriving

    build-depends:
        , array
        , base                 >=4.17    && <5
        , bytestring
        , composition-prelude  >=1.1.0.1
        , containers           >=0.6.3.1
        , deepseq              >=1.4.3.0
        , dom-lt
        , extra                >=1.7.4
        , microlens
        , microlens-mtl        >=0.1.8.0
        , mtl                  >=2.2.2
        , prettyprinter        >=1.7.0
        , split                >=0.2.0.0
        , text                 >=1.2.0.0
        , transformers

library as
    import:          warn
    exposed-modules: H
    other-modules:
        As
        Nasm

    hs-source-dirs:  as
    build-depends:
        , apple
        , base
        , bytestring
        , prettyprinter
        , process
        , temporary
        , text

library jit
    import:             warn
    exposed-modules:
        Hs.FFI
        JIT
        Sys.DL

    other-modules:
        Asm.Aarch64.Byte
        Asm.X86.Byte

    hs-source-dirs:     jit
    build-tool-depends:
        , c2hs:c2hs
        , hsc2hs:hsc2hs

    build-depends:
        , apple
        , base
        , bytestring
        , containers
        , extra
        , prettyprinter  >=1.7.0
        , text
        , unix

library apple-repl
    import:          warn
    exposed-modules: REPL
    other-modules:   QC
    hs-source-dirs:  repl
    build-depends:
        , apple
        , base
        , bytestring
        , containers
        , criterion
        , directory
        , haskeline
        , jit
        , libffi
        , prettyprinter
        , QuickCheck
        , split          >=0.2.0.0
        , text
        , transformers

foreign-library apple
    import:             warn
    type:               native-shared
    build-tool-depends: c2hs:c2hs >=0.19.1
    hs-source-dirs:     lib
    other-modules:      E
    include-dirs:       include
    install-includes:
        apple.h
        m.h

    build-depends:
        , apple
        , base
        , bytestring     >=0.11.0.0
        , jit
        , prettyprinter  >=1.7.0
        , text

    if os(linux)
        lib-version-info: 1:0:0

    if os(windows)
        options: standalone

executable atc
    import:          warn
    main-is:         Main.hs
    hs-source-dirs:  app
    other-modules:   Paths_apple
    autogen-modules: Paths_apple
    build-depends:
        , apple
        , base
        , optparse-applicative  >=0.13.0.0

executable writeo
    import:          warn
    main-is:         Main.hs
    hs-source-dirs:  exe
    other-modules:   Paths_apple
    autogen-modules: Paths_apple
    build-depends:
        , as
        , base
        , optparse-applicative  >=0.14.0.0
        , text

executable arepl
    import:         warn
    main-is:        Main.hs
    hs-source-dirs: run
    build-depends:
        , apple
        , apple-repl
        , base
        , directory
        , filepath
        , haskeline
        , text
        , transformers

test-suite repltest
    import:         warn
    type:           exitcode-stdio-1.0
    main-is:        Test.hs
    hs-source-dirs: i
    ghc-options:    -threaded -rtsopts "-with-rtsopts=-N -k1k"
    build-depends:
        , apple-repl
        , base
        , bytestring
        , haskeline
        , silently
        , tasty
        , tasty-golden
        , temporary
        , transformers

test-suite apple-test
    import:         warn
    type:           exitcode-stdio-1.0
    main-is:        Z.hs
    hs-source-dirs: test
    ghc-options:    -threaded -rtsopts "-with-rtsopts=-N -k1k"
    build-depends:
        , apple
        , base
        , bytestring
        , fast-arithmetic
        , hypergeometric    >=0.1.4.0
        , jit
        , QuickCheck
        , tasty
        , tasty-hunit
        , tasty-quickcheck

test-suite apple-o
    import:         warn
    type:           exitcode-stdio-1.0
    main-is:        Test.hs
    hs-source-dirs: of
    ghc-options:    -rtsopts -with-rtsopts=-k1k
    build-depends:
        , as
        , base
        , directory
        , filepath
        , process
        , tasty >=1.5.4
        , tasty-hunit
        , temporary
        , text

benchmark apple-bench
    import:         warn
    type:           exitcode-stdio-1.0
    main-is:        Bench.hs
    hs-source-dirs: bench
    ghc-options:    -rtsopts
    build-depends:
        , apple
        , base
        , bytestring
        , criterion
        , deepseq
        , erf
        , hypergeometric  >=0.1.2.0
        , jit
        , statistics
